# Generated by Django 4.2.3 on 2023-07-29 03:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
